// Generated by Wrangler on Thu Sep 12 2024 14:11:23 GMT+0100 (British Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	NEXTAUTH_SECRET: string;
	NEXTAUTH_URL: string;
	GROQ_API_KEY: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	R2_ACCOUNT_ID: string;
	MY_BUCKET: R2Bucket;
	DATABASE: D1Database;
}
