// Generated by Wrangler on Sun Sep 08 2024 23:26:35 GMT+0100 (British Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	NEXTAUTH_SECRET: string;
	DATABASE: D1Database;
}
